---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prysm-webhook-service
  namespace: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prysm-webhook-service
  template:
    metadata:
      labels:
        app: prysm-webhook-service
    spec:
      containers:
      - name: prysmwebhook
        image: ghcr.io/cobaltcore-dev/prysm-wh:v1.2.3
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
        env:
        - name: SIDECAR_IMAGE
          value: "ghcr.io/cobaltcore-dev/prysm:v1.2.3"
        imagePullPolicy: Always
      volumes:
      - name: certs
        secret:
          secretName: prysm-webhook-cert
