apiVersion: v1
kind: Secret
metadata:
  name: rgw-sidecar-env
  namespace: rook-ceph
type: Opaque
stringData:
  LOG_FILE_PATH: "/var/log/ceph/ops-log.log"
  SOCKET_PATH: ""
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  NATS_SUBJECT: "rgw.s3.ops"
  NATS_METRICS_SUBJECT: "rgw.s3.ops.aggregated.metrics"
  LOG_TO_STDOUT: "false"
  LOG_RETENTION_DAYS: "2"
  MAX_LOG_FILE_SIZE: "10"
  PROMETHEUS_PORT: "9090"
  POD_NAME: "dummy-pod"
  IGNORE_ANONYMOUS_REQUESTS: "true"

# TRACK_EVERYTHING: "true"
  TRACK_REQUESTS_DETAILED: "true"
  TRACK_REQUESTS_PER_USER: "true"
  TRACK_REQUESTS_PER_BUCKET: "true"
  TRACK_REQUESTS_PER_TENANT: "true"
  TRACK_REQUESTS_BY_METHOD_DETAILED: "true"
  TRACK_REQUESTS_BY_METHOD_PER_USER: "true"
  TRACK_REQUESTS_BY_METHOD_PER_BUCKET: "true"
  TRACK_REQUESTS_BY_METHOD_PER_TENANT: "true"
  TRACK_REQUESTS_BY_METHOD_GLOBAL: "true"
  TRACK_REQUESTS_BY_OPERATION_DETAILED: "true"
  TRACK_REQUESTS_BY_OPERATION_PER_USER: "true"
  TRACK_REQUESTS_BY_OPERATION_PER_BUCKET: "true"
  TRACK_REQUESTS_BY_OPERATION_PER_TENANT: "true"
  TRACK_REQUESTS_BY_OPERATION_GLOBAL: "true"
  TRACK_REQUESTS_BY_STATUS_DETAILED: "true"
  TRACK_REQUESTS_BY_STATUS_PER_USER: "true"
  TRACK_REQUESTS_BY_STATUS_PER_BUCKET: "true"
  TRACK_REQUESTS_BY_STATUS_PER_TENANT: "true"
  TRACK_BYTES_SENT_DETAILED: "true"
  TRACK_BYTES_SENT_PER_USER: "true"
  TRACK_BYTES_SENT_PER_BUCKET: "true"
  TRACK_BYTES_SENT_PER_TENANT: "true"
  TRACK_BYTES_RECEIVED_DETAILED: "true"
  TRACK_BYTES_RECEIVED_PER_USER: "true"
  TRACK_BYTES_RECEIVED_PER_BUCKET: "true"
  TRACK_BYTES_RECEIVED_PER_TENANT: "true"
  TRACK_ERRORS_DETAILED: "true"
  TRACK_ERRORS_PER_USER: "true"
  TRACK_ERRORS_PER_BUCKET: "true"
  TRACK_ERRORS_PER_TENANT: "true"
  TRACK_ERRORS_PER_STATUS: "true"
  TRACK_REQUESTS_BY_IP_DETAILED: "true"
  TRACK_REQUESTS_BY_IP_PER_TENANT: "true"
  TRACK_REQUESTS_BY_IP_BUCKET_METHOD_TENANT: "true"
  TRACK_REQUESTS_BY_IP_GLOBAL_PER_TENANT: "true"
  TRACK_BYTES_SENT_BY_IP_DETAILED: "true"
  TRACK_BYTES_SENT_BY_IP_PER_TENANT: "true"
  TRACK_BYTES_SENT_BY_IP_GLOBAL_PER_TENANT: "true"
  TRACK_BYTES_RECEIVED_BY_IP_DETAILED: "true"
  TRACK_BYTES_RECEIVED_BY_IP_PER_TENANT: "true"
  TRACK_BYTES_RECEIVED_BY_IP_GLOBAL_PER_TENANT: "true"
  TRACK_LATENCY_DETAILED: "true"
  TRACK_LATENCY_PER_USER: "true"
  TRACK_LATENCY_PER_BUCKET: "true"
  TRACK_LATENCY_PER_TENANT: "true"
  TRACK_LATENCY_PER_METHOD: "true"
  TRACK_LATENCY_PER_BUCKET_AND_METHOD: "true"