apiVersion: v1
kind: Secret
metadata:
  name: rgw-sidecar-env
  namespace: rook-ceph
type: Opaque
stringData:
  LOG_FILE_PATH: "/var/log/ceph/ops-log.log"
  SOCKET_PATH: ""
  NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  NATS_SUBJECT: "rgw.s3.ops"
  NATS_METRICS_SUBJECT: "rgw.s3.ops.aggregated.metrics"
  LOG_TO_STDOUT: "false"
  LOG_RETENTION_DAYS: "2"
  MAX_LOG_FILE_SIZE: "10"
  PROMETHEUS_PORT: "9090"
  POD_NAME: "dummy-pod"
  IGNORE_ANONYMOUS_REQUESTS: "true"

  TRACK_REQUESTS_BY_IP: "true"
  TRACK_BYTES_SENT_BY_IP: "true"
  TRACK_BYTES_RECEIVED_BY_IP: "true"
  TRACK_ERRORS_BY_IP: "true"
  TRACK_ERRORS_BY_USER: "true"
  TRACK_REQUESTS_BY_METHOD: "true"
  TRACK_REQUESTS_BY_OPERATION: "true"
  TRACK_REQUESTS_BY_STATUS: "true"
  TRACK_REQUESTS_BY_BUCKET: "true"
  TRACK_REQUESTS_BY_USER: "true"
  TRACK_REQUESTS_BY_TENANT: "false"
  TRACK_ERRORS_BY_BUCKET: "false"
  TRACK_ERRORS_BY_STATUS: "false"
  TRACK_LATENCY_BY_USER: "false"
  TRACK_LATENCY_BY_BUCKET: "false"
  TRACK_LATENCY_BY_TENANT: "false"